language: generic
sudo: required
services:
  - docker

before_install:
   - docker build -t leeseungryeol/react-test-app -f ./frontend/Dockerfile.dev ./frontend
   
script: 
   - docker run -e CI=true leeseungryeol/react-test-app npm test

after_success:
  - doker build -t leeseungryeol/docker-frontend ./frontend
  - doker build -t leeseungryeol/docker-backend ./backend
  - docker build -t leeseungryeol/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" || docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push leeseungryeol/docker-frontend
  - docker push leeseungryeol/docker-backend
  - docker push leeseungryeol/docker-nginx